### PR TITLE
Package sagenb normally

### PR DESCRIPTION
**Pull request by jdemeyer**
Package sagenb as a normal Python package, see http://trac.sagemath.org/ticket/14840

### CODE REVIEW

**Comment by jdemeyer** [comment]
Note that I removed `webassets` from SageNB since I didn't see any evidence that it's actually used. I guess that it was used in the past but no longer.

**Comment by kcrisman** [comment]
> Note that I removed webassets from SageNB since I didn't see any evidence
> that it's actually used. I guess that it was used in the past but no longer.
>

See http://trac.sagemath.org/ticket/16736 regarding this.

**Comment by jdemeyer** [comment]
Comment https://groups.google.com/forum/#!msg/sage-devel/fEeGgVWuk7I/nDOHbclqLUAJ indicates that `webassets` is used by the `newui` branch but not in vanilla SageNB.

**Comment by kcrisman** [comment]
> Comment
> https://groups.google.com/forum/#!msg/sage-devel/fEeGgVWuk7I/nDOHbclqLUAJ
> indicates that webassets is used by the newui branch but not in vanilla
> SageNB.
>
Correct, that's what I was referring to - so if one removes webassets, then
somewhere one needs to indicate how to install it (pip, I assume), perhaps
what version.  Which would be just fine by me.

**Comment by jdemeyer** [comment]
> somewhere

Where do you think this be done? It's trivial to install `webassets` in Sage:
```
./sage --pip install webassets
```

**Comment by kcrisman** [comment]
> somewhere
>
> Where do you think this be done? It's trivial to install webassets in
> Sage:
>
> ./sage --pip install webassets
>
> Right, so that should just be mentioned somewhere in the sagenb
documentation.  It could be a one-line edit in the readme or something.
That's all I meant; currently the sagenb doc doesn't mention pip, I don't
think.

**Comment by jdemeyer** [comment]
The most recent commit on the `newui` branch was on 20 Dec 2013. Do you think that people are still interested in that? If the answer is "no", there is no point in documenting something which is only meant for that branch.

**Comment by novoselt** [comment]
Given that we are switching away from sagenb altogether and the point of maintaining it is to keep old users happy, I personally see zero benefit in doing anything to support completely new interfaces to sagenb.

**Comment by kcrisman** [comment]
Nonetheless there are people occasionally asking about this (I mean newui),
so I don't see why it's a problem to just include a brief note about it.
That said, I won't be able to do that for the next several days to week.

**Comment by ppurka** [comment]
Newui is quite unmaintained. The last commit made in that direction was
some effort by me to update it to the latest changes in sagenb. There are
subtle bugs in newui, that are encountered only when one starts using it
more than occasionally, so I think if you want to make webassets optional,
then it is OK.
On Apr 9, 2016 4:51 AM, "kcrisman" <notifications@github.com> wrote:

Nonetheless there are people occasionally asking about this (I mean newui),
so I don't see why it's a problem to just include a brief note about it.
That said, I won't be able to do that for the next several days to week.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/sagemath/sagenb/pull/371#issuecomment-207601210>

**Comment by jdemeyer** [comment]
See #372 for improving the README of the newui branch.

**Comment by dimpase** [comment]
after following the instructions to install, I started the nb and ran
     2^1000

and got
     
       	Error typesetting mathematics
       107150860718626732094842504906000181056140481170553360744375038837035105\
       ...

could it be something related to mathjax removal? I'm on Linux, using Chrome.

**Comment by jdemeyer** [comment]
> after following the instructions to install

Use http://trac.sagemath.org/ticket/14840 to install SageNB.

**Comment by dimpase** [comment]
I don't see how we can move forward with #14840. What's the point of all these flask and co packages installed as Sage packages?

**Comment by jdemeyer** [comment]
If you have comments about the Sage ticket, it's better to post your comment there.

In any case, the answer is: they are packages because SageNB depends on them.

**Pull request merged**
