### PR TITLE
Disable notification emails by default

### PR DESCRIPTION
**Pull request by jdemeyer**

### CODE REVIEW

**Comment by kcrisman** [comment]
Okay, I'll test this out today or tomorrow.  Quick look seems just fine, I just want to test that a) it works and b) I can easily put a few email addresses in the list.

**Comment by kcrisman** [comment]
Works great, as expected.  Only issue I see is that if someone had the beta version it would remember the previous config and still send to `root@localhost`, but for anyone just upgrading normally should be fine; I don't think there is a way to prevent that.

**Comment by kcrisman** [comment]
(That is to say I will make a new sagenb package if you agree that is not a problem.)

**Comment by jdemeyer** [comment]
> Only issue I see is that if someone had the beta version it would remember the previous config and still send to root@localhost, but for anyone just upgrading normally should be fine;
I think that's fine.

**Comment by jdemeyer** [comment]
> I will make a new sagenb package

Please do!

**Pull request merged**
