### PR TITLE
Copy instead of move such that owner is correct

### PR DESCRIPTION
**Pull request by jdemeyer**
Fix for #348.

### CODE REVIEW

**Comment by kcrisman** [comment]
The change seems very minimal.  I'm glad you tried to see if this works
properly!  As a dumb question, do all the processes still have the right
permissions to do the copy and unlink?

**Comment by jdemeyer** [comment]
All I can say is that it seems to work...

**Comment by jdemeyer** [comment]
With this pull request, the resulting code is actually closer to what it was before #340: in #340, I "simplified" the copy+unlink to a move but it turns out this was a mistake.

**Comment by kcrisman** [comment]
> With this pull request, the resulting code is actually closer to what it
> was before #340 <https://github.com/sagemath/sagenb/pull/340>: in #340
> <https://github.com/sagemath/sagenb/pull/340>, I "simplified" the
> copy+unlink to a move but it turns out this was a mistake.
>

Good point.  If someone else (e.g. Andrey, who merged the first one)
agrees, we can merge this.

**Comment by novoselt** [comment]
Agree!

**Comment by jdemeyer** [comment]
Don't forget to close #348 (for this reason, I like the Trac model better, where issues and pull requests are really the same thing)

**Comment by novoselt** [comment]
Agreed as well. Notifications (or their lack) also keep confusing me on github.

**Pull request merged**
