### PR TITLE
No has key

### PR DESCRIPTION
**Pull request by fchapoton**
remove any use of has_key, which is python2 only, replaced by "x in y"

### CODE REVIEW

**Comment by fchapoton** [comment]
this is on top of the "raise statement" branch, so to be merged after it

**Comment by dimpase** [comment]
Could you provide a quick explanation/link about this has_key story?

**Comment by fchapoton** [comment]
Yes, this is because has_key is removed in python3, and should be replaced, see

https://docs.python.org/3.1/whatsnew/3.0.html

and

http://stackoverflow.com/questions/1323410/has-key-or-in

**Comment by dimpase** [comment]
OK, good.

**Pull request merged**
