### PR TITLE
change import flask.ext.babel to flask_babel

### PR DESCRIPTION
**Pull request by fchapoton**
for compatibility with more recent flask

### CODE REVIEW

**Comment by dimpase** [comment]
this is towards resolving #437, right?

**Comment by dimpase** [comment]
how far are you willing to push it, it is more work (in fact I tried and gave up some time ago)?

**Comment by kiwifb** [comment]
Actually this particular message is generated by the new flask rather than flask-babel. So it is unrelated to #437 in so far that #437 that new flask-babel with an old flask.

Now that I am on the latest flask in sage-on-gentoo my doctest results are seriously polluted in some place you wouldn't have ever thought sagenb would be involved.

**Comment by dimpase** [comment]
I'm all for downgrading sagenb to optional. (Do you know a sage-on-gentoo user using sagenb?)

**Comment by kiwifb** [comment]
Not on the top of my head. If we do that we have to evaluate what happens when sagenb is removed. We have fixed a lot of dependencies but I don't know if there are any left.

**Comment by kiwifb** [comment]
One glaring example revealed by my polluted doctests
```
sage: S = ClusterSeed(['A',4])
sage: S.interact()
'The interactive mode only runs in the Sage notebook.'
```
If sagenb becomes optional some of those bits become optional too unless someone cares enough to port them to some new interfaces. This is at https://github.com/sagemath/sage/blob/master/src/sage/combinat/cluster_algebra_quiver/cluster_seed.py#L1043

**Comment by kiwifb** [comment]
`sage -t --all` currently requires sagenb
```
fbissey@moonloop ~ $ sage -tp 8 --long --all
Running doctests with ID 2018-01-26-14-16-21-77ff5f12.
Using --optional=optional,sage
Doctesting entire Sage library.
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/sage-runtests", line 105, in <module>
    err = DC.run()
  File "/usr/lib64/python2.7/site-packages/sage/doctest/control.py", line 1096, in run
    self.add_files()
  File "/usr/lib64/python2.7/site-packages/sage/doctest/control.py", line 643, in add_files
    sagenb_loc = working_set.find(Requirement.parse('sagenb')).location
AttributeError: 'NoneType' object has no attribute 'location'
```

**Comment by kcrisman** [comment]
> I'm all for downgrading sagenb to optional.

I don't understand why that is necessary if the only problem is with up-to-date Flask.  We still get quite a few questions about sagenb various places.

On the other hand the various things of that interactive nature should be portable to Jupyter, I would think (though I noticed before giving a talk recently that apparently some widgets in Jupyter are different than in sagenb, I mean some of the syntax for widgets like `(1,100)`).

**Pull request merged**
