### PR TITLE
Remove unneeded imports

### LINKED ISSUE #336: load("object.sobj") does not work anymore
Because `load` in the notebook is tied to the function loading a source code file rather than objects, as it is the case on the command line.

First detected in Sage 6.5.beta5, not present in 6.4.

### PR DESCRIPTION
**Pull request by jdemeyer**
Fix #336

### CODE REVIEW

**Comment by kcrisman** [comment]
Unfortunately I can't test this immediately, but based on the symptoms I'm sure this will solve it.  @novoselt or @gutow I would be happy to have you test this (you should be able to just make the change "by hand" in your sagenb because it's so small of a change) and then I or @novoselt can merge it.

**Comment by novoselt** [comment]
Why `interact` import was removed as well? Will test later today.

**Comment by jdemeyer** [comment]
```interacts``` is parts of the ```import *```

**Comment by kcrisman** [comment]
Thanks for reviewing this!  Remind me via email later this week and I will make up a package for http://trac.sagemath.org/ticket/17645.

**Pull request merged**
