### PR TITLE
Add ldap_custom_filter option

### PR DESCRIPTION
**Pull request by rmartinjak**
Not tested at all, someone with a working LDAP setup should verify that this works.

### CODE REVIEW

**Comment by kcrisman** [comment]
I agree that this seems appropriate on the sagenb side, and also that it needs some testing.  Can you think of any obvious security holes such a filter might have? I know very little about LDAP.

**Comment by rmartinjak** [comment]
The only thing I can think of would be information leakage; if
a) the filter is known
b) a valid LDAP username is known
then one could infer whether the user matches the filter by sagenb's reply to a login attempt "password incorrect" == user matches, "username not known" == user doesn't match).

**Comment by ppurka** [comment]
Does sagenb print this information? Or, is it some other package inside
sagenb?

If it is sagenb, we should change the error message to "incorrect username
or password" in both cases. That is the standard way to not leak
information on whether the user ID exists in the system.

If it is some other package, we can create a patch.

**Comment by rmartinjak** [comment]
It's here: https://github.com/sagemath/sagenb/blob/master/sagenb/data/sage/html/login.html#L64-L83

**Comment by kcrisman** [comment]
```
            {% if username_error %}
            <span style="color:red">{{ gettext('Error') }}: </span>{{ gettext('Username is not in the system') }}
            {% endif %}
```

and similarly for password, so yes this is in principle a possibility.

**Comment by kcrisman** [comment]
I think I'll ask for an update of the code @rmartinjak pointed to to tweak the error message a bit so it's less obvious what the error is from.

**Pull request closed without merging**
