### PR TITLE
Send e-mail notifications to configured address(es)

### PR DESCRIPTION
**Pull request by rmartinjak**
Let's be honest, how often do you log in to check a running notebook's output for errors?

With the code attached,
- the admin(s) can configure a list of notification recipients in "Settings -> Notebook Settings"
- uncaught exceptions automatically produce a notification and present the user a "500: Internal server error" page
- sending a notification e-mail to the admin(s) can be done with e.g.

``` python
from sagenb.notebook.notification import logger
logger.error("something went wrong!")
```

or simply by throwing an exception (that is not caught).

Note: I had to remove the forking-related code in `sagenb.notebook.sage_email` in order to get this to work. This shouldn't be a problem since twisted sends e-mails asynchronously.

### CODE REVIEW

**Comment by jdemeyer** [comment]
I am a bit worried about who could receive this `root@localhost` e-mail. Imagine users on a shared server using their own personal Sage running their own personal Notebook. Then it's probably not appropriate to send e-mail to `root@localhost`.

I would much prefer to send no e-mails by default.

**Comment by kcrisman** [comment]
Well, the emails sent are not really that informative, I think - try it yourself!  I suppose that the easiest fix to this is to just have no default for this option; I'm not sure I want to try to add yet another checkbox, nor do I have time now to do that.  I would entertain a PR, of course.

**Comment by jdemeyer** [comment]
The more I think about this, the more I am convinced that sending e-mails to `root@localhost` is a bad idea. We simply don't know who `root@localhost` is and whether he really wants these e-mails.

**Comment by kcrisman** [comment]
I was wondering about that, but I don't have enough sysadmin experience to suggest a different default.  I was figuring that anyone using this as a server would have those rights to read that email...

Anyway, I think the easiest thing to do is to change the doc and default to an empty string, which would have a try/catch that then just doesn't send an email.  As I said, I don't have time to create yet another configuration button right now.

**Comment by kcrisman** [comment]
As I say above:

> So this is of limited utility unless someone is watching on something like localhost that is going to actually accept these emails - which should be the case for well-administered servers, of course!

**Comment by jdemeyer** [comment]
> I was figuring that anyone using this as a server would have those rights to read that email...

The person who administers the server (the box) could very well be somebody else than the person who runs the Sage Notebook server (the software).

Anyway, I'm happy of course with the "empty" default for e-mail address.

**Comment by kcrisman** [comment]
Great!  Can you submit the PR for that?  I can review it but am in the middle of a big project I really need to finish by tomorrow.

One thing; what do you think would happen in that event if something does get sent?  My worry is that it will try to send an email upon an error, have the empty email address, encounter some error because it tried to send to a blank email address, and then raise a different exception - either triggering an unending cascade of emails because of the exceptions, or crashing the server, or ... or something.  So if you could test that first I'd be grateful.

(Note that it's actually nontrivial to test the error part of this change; you have to go break something in your local sagenb repo and then try to use that anyway - I think I removed some exception that is now caught for finding usernames or something.  At least, I couldn't find anything that is 'normally' broken on sagenb that would send these.)

**Comment by jdemeyer** [comment]
An easy (and safe?) way to intentionally break sagenb is
```
chmod 000 .sage/sage_notebook.sagenb
```
while the server is running.

**Comment by kcrisman** [comment]
Hmm, I was thinking more of a *user* error that would crash it.  Does running that actually send the email?  I guess it would make any action be disallowed...

**Comment by jdemeyer** [comment]
>Does running that actually send the email?

Yes.

**Comment by jdemeyer** [comment]
See #338

**Pull request merged**
