### PR TITLE
Fixes for Cythonized srange(), Sage Trac #20094

### PR DESCRIPTION
**Pull request by jdemeyer**
Fixes for http://trac.sagemath.org/ticket/20094 (but should work with or without that ticket).

### CODE REVIEW

**Comment by kcrisman** [comment]
So is `types.GeneratorType` what `srange()` used to be and now it's a type of `collections.Iterator` in the Cythonized version?  I'm not too familiar with that part of interact.py so if you have the quick story on that change I'd appreciate it, I don't have a problem with the first part.

**Comment by jdemeyer** [comment]
To be more precise: `types.GeneratorType` describes a Python generator and only that. The type `collections.Iterator` is more general and matches anything that can be iterated. So clearly, this is what should be used here.

**Comment by kcrisman** [comment]
> To be more precise: types.GeneratorType describes a Python generator and
> only that. The type collections.Iterator is more general and matches
> anything that can be iterated.
>

Such as a Cython construction, presumably?


> So clearly, this is what should be used here.
>
Sounds good to me, I'll be sure to test a few things but don't anticipate
any problems.

**Comment by kcrisman** [comment]
Do you want to also change

    from sagenb.misc.misc import srange 

in interact.py?

**Comment by kcrisman** [comment]
I'm also curious about whether we should change

        * ``u = generator`` - a slider (up to `10000` steps)

By the way, what test failed?  I couldn't find any with `yield` or `xsrange` in sagenb.

**Comment by jdemeyer** [comment]
> Do you want to also change
> 
> from sagenb.misc.misc import srange 
> 
> in interact.py?

Note that this an import from `sagenb`. So there is no need to change that.

**Comment by jdemeyer** [comment]
> By the way, what test failed?

Several doctests which involve the `(a..b)` notation, which the preparser changes into `ellipsis_iter(something)`. With Sage Trac 20094, that is now implemented in Cython so it no longer matches the `types.GeneratorType` type. It does match the `collections.Iterator` type.

**Comment by jdemeyer** [comment]
> * ``u = generator`` - a slider (up to `10000` steps)

Maybe change "generator" to "iterator"?

**Comment by kcrisman** [comment]
Okay, that all sounds good - I didn't realize `(1..2)` returned something different than `[1..2]` because I only use the latter.

**Pull request merged**
