### PR TITLE
Fix undefined user and version in error message

### LINKED ISSUE #309: undefined user and version in app.message
There are a few peculiarities about the [error page](https://github.com/sagemath/sagenb/blob/master/sagenb/flask_version/base.py#L72).  As an easy example, go to http://localhost:8080/forgotpass in a local Sage (which presumably won't have account recovery enabled).

```
 def message(self, msg, cont='/', username=None, **kwds):
"""Returns an error message to the user."""
    template_dict = {'msg': msg, 'cont': cont, 'username': username}
    template_dict.update(kwds)
```

1. The user seems to be `None`.  Presumably because none of the uses of this (such as the ones in `flask_version/worksheet.py` ever pass the username in!
2. There is no `sage_version` defined.  That should be fairly easy to fix.

### PR DESCRIPTION
**Pull request by kcrisman**
This fixes #309.  

My apologies for the merge commits, this touched on the same stuff as #308 and I wasn't sure how to handle that without waiting until that was merged in master (which however happened quicker than I thought.)

### CODE REVIEW

**Comment by kcrisman** [comment]
@gutow @novoselt this is a fairly marginal change, though I can see it possibly (?) interfering with more important things like #328.  Any comments?

**Comment by kcrisman** [comment]
@novoselt I merged #350 - can you take a look at this one?  Thanks!

**Comment by novoselt** [comment]
OK, looks good to me! I will not merge it to avoid interference with your plans. Is there a trac ticket yet about upgrade of SageNB?

**Comment by kcrisman** [comment]
Actually, please do merge - I have few other plans as you can see by looking at the pull request side; Jonathan G. isn't ready to get the proxy stuff up to date - and unfortunately even though the conflicts are probably trivial I know I won't have time to gitify the conflicts properly either.

Unless you wanted to look at testing the Ukrainian translation to see how many things are still left untranslated - if it's not too many we could merge that one too.

Also, see http://trac.sagemath.org/ticket/19616 - the real thing is merging @kiwifb's #351 but I won't be able to look at that until at least a couple days from now, although I hardly doubt that it works!  Just want to test it myself to be sure.

**Comment by novoselt** [comment]
I don't/can't commit to testing any stuff in the next month or so but would be happier if these changes made it to 6.10. For translation I think if technical side is OK it is better to have partial than none at all, please merge it.

**Pull request merged**
