### PR TITLE
Make setup.py executable

### PR DESCRIPTION
**Pull request by jdemeyer**

### CODE REVIEW

**Comment by kcrisman** [comment]
I don't see why this would be a problem, but can you give some context?  Thanks!

**Comment by jdemeyer** [comment]
> can you give some context?

There is nothing deep here: `setup.py` is a script which is executed, so it should be executable.

**Comment by jdemeyer** [comment]
You know the `configure` scripts which come with many (non-Python) packages? Those are always executable and `setup.py` should be executable for the same reason that `configure` is executable.

**Comment by kcrisman** [comment]
Okay, this sounds reasonable.  What is the time frame - I can't do tons of
sagenb TLC at the moment but let me know.  Also regarding the other PR,
which I haven't gotten to look at yet.

**Pull request merged**
