### PR TITLE
some more print, raise and except to python2/3 compatible standard

### PR DESCRIPTION
**Pull request by fchapoton**
In this branch:

* some more prints (but not all) converted to python3. Some are kind of special, because the change    happen inside strings that will be fed to python somewhere
* a few raise that were missed in previous commits
* a few except, idem

### CODE REVIEW

**Comment by dimpase** [comment]
As long as twisted is not ported to Python 3, all of this is very low priority, I think...

**Comment by fchapoton** [comment]
yes, sure. But nevertheless, I would like to try to advance things a little bit.

**Comment by fchapoton** [comment]
any objection to merge ?

**Comment by dimpase** [comment]
it's a bit inconsistent: you remove some comments with print, and edit other such comments.
I'd rather keep all comments...

**Comment by fchapoton** [comment]
I am not willing to spend time to turn *commented code* to python3
standard. And what would be the use of commented prints that do no longer
work ?

Seriously, turning to py3 will be hard enough, let us try not to spend too
much time on trivial things.

2016-05-21 17:00 GMT+02:00 Dima Pasechnik <notifications@github.com>:

**Comment by dimpase** [comment]
Do you test your changes? I.e. I can merge them in a private copy, see if sagenb loads and runs trivial things, but I prefer to do this in big chunks.

**Pull request merged**
