### PR TITLE
unicode had no u

### PR DESCRIPTION
**Pull request by fchapoton**
adding u prefix for some unicode strings in the doc

### CODE REVIEW

**Comment by jdemeyer** [comment]
This is causing doctest failures:
```
sage -t --long local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py", line 715, in sagenb.notebook.worksheet.Worksheet.name
Failed example:
    W.name()
Expected:
    u'\u011b\u0161\u010d\u0159\u017e\xfd\xe1\xed\xe9\u010f\u010e'
Got:
    u'\xc4\x9b\xc5\xa1\xc4\x8d\xc5\x99\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9\xc4\x8f\xc4\x8e'
**********************************************************************
```

```
sage -t --long local/lib/python2.7/site-packages/sagenb/notebook/cell.py
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/cell.py", line 626, in sagenb.notebook.cell.TextCell.plain_text
Failed example:
    C.plain_text()
Expected:
    u'\u011b\u0161\u010d\u0159\u017e\xfd\xe1\xed\xe9\u010f\u010e'
Got:
    u'\xc4\x9b\xc5\xa1\xc4\x8d\xc5\x99\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9\xc4\x8f\xc4\x8e'
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/cell.py", line 1191, in sagenb.notebook.cell.Cell.edit_text
Failed example:
    C.edit_text()
Expected:
    u'{{{id=0|\n\u011b\u0161\u010d\u0159\u017e\xfd\xe1\xed\xe9\u010f\u010e\n///\n\u011b\u0161\u010d\u0159\u017e\xfd\xe1\xed\xe9\u010f\u010e\n}}}'
Got:
    u'{{{id=0|\n\xc4\x9b\xc5\xa1\xc4\x8d\xc5\x99\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9\xc4\x8f\xc4\x8e\n///\n\xc4\x9b\xc5\xa1\xc4\x8d\xc5\x99\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9\xc4\x8f\xc4\x8e\n}}}'
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/cell.py", line 1797, in sagenb.notebook.cell.Cell.output_text
Failed example:
    C.output_text()
Expected:
    u'<pre class="shrunk">\u011b\u0161\u010d\u0159\u017e\xfd\xe1\xed\xe9\u010f\u010e</pre>'
Got:
    u'<pre class="shrunk">\xc4\x9b\xc5\xa1\xc4\x8d\xc5\x99\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9\xc4\x8f\xc4\x8e</pre>'
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/cell.py", line 1799, in sagenb.notebook.cell.Cell.output_text
Failed example:
    C.output_text(raw=True)
Expected:
    u'\u011b\u0161\u010d\u0159\u017e\xfd\xe1\xed\xe9\u010f\u010e'
Got:
    u'\xc4\x9b\xc5\xa1\xc4\x8d\xc5\x99\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9\xc4\x8f\xc4\x8e'
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/cell.py", line 1997, in sagenb.notebook.cell.Cell.set_introspect_html
Failed example:
    C.introspect_html()
Expected:
    u'\u011b\u0161\u010d\u0159\u017e\xfd\xe1\xed\xe9\u010f\u010e'
Got:
    u'\xc4\x9b\xc5\xa1\xc4\x8d\xc5\x99\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9\xc4\x8f\xc4\x8e'
**********************************************************************
```

```
sage -t --long local/lib/python2.7/site-packages/sagenb/notebook/template.py
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/template.py", line 129, in sagenb.notebook.template.template
Failed example:
    'Gr\xc3\xb6bner' in s.encode('utf-8')
Expected:
    True
Got:
    False
**********************************************************************
```

Please fix them or I will revert this pull request.

**Comment by dimpase** [comment]
Is this a kind of python2/3 incompatibility? I don't know.

**Comment by fchapoton** [comment]
I have no objection to undo all this. If you can do that easily, please proceed.

**Comment by jdemeyer** [comment]
Reverted in https://github.com/sagemath/sagenb/commit/13d667f1a3f30d089603856cafbf2922b6dc33bd

**Comment by embray** [comment]
It looks to me like what's really needed is better support in the APIs being used for supporting non-unicode strings in Python 2 compatibly with unicode strings on Python 3.

**Pull request merged**
