### PR TITLE
Add deprecation warning

### PR DESCRIPTION
**Pull request by timokau**
As discussed in https://trac.sagemath.org/ticket/25852. I'm unsure how the localization and templating works. Am I doing this right?

### CODE REVIEW

**Comment by timokau** [comment]
Ping

**Comment by jdemeyer** [comment]
I thought that you were going to change the message?

**Comment by timokau** [comment]
I did change it to

> This notebook is deprecated. Click here for details.

As discussed or did I misunderstand something?

**Comment by kcrisman** [comment]
This one seems okay, though perhaps the mo files need to be regenerated and/or other translations ... but those hardly are a stumbling block to merging.  I am not able to actually test it builds but assuming yes this should be fine.

**Comment by timokau** [comment]
Because they reference line numbers in a file where I added a line. IIRC I manually corrected those.

**Comment by dimpase** [comment]
Great, thanks!

**Pull request merged**
