### PR TITLE
Restore change for pexpect 4+ upgrade.

### PR DESCRIPTION
**Pull request by kiwifb**
New pull request for http://trac.sagemath.org/ticket/10295 and http://trac.sagemath.org/ticket/19616.

### CODE REVIEW

**Comment by jdemeyer** [comment]
Not really `Needs Review`, it's already reviewed the first time it was merged.

**Comment by kcrisman** [comment]
Well, it wasn't actually tested independently by anyone other than @kiwifb , at least not that I can tell by reading #351: @novoselt says he didn't actually try it.  If you did test this necessity while testing the relevant Trac ticket, I'll happily merge, @jdemeyer !  Otherwise testing this is one on a long list of small projects I need to do today before final exams begin.

**Comment by jdemeyer** [comment]
> If you did test this necessity while testing the relevant Trac ticket

Yes, I tested http://www.math-cs.gordon.edu/~kcrisman/sagenb-0.11.5.1.tar while testing http://trac.sagemath.org/ticket/10295

**Comment by kcrisman** [comment]
Awesome, thanks for the notification.

**Pull request merged**
