### PR TITLE
fix that allow to update flask

### PR DESCRIPTION
**Pull request by fchapoton**
This simple change seem to fix the known issue with flask update.

### CODE REVIEW

**Comment by fchapoton** [comment]
This may break the localisation (language settings)..

**Comment by embray** [comment]
I think this is probably fine.  The `notebook` variable is a module-level global anyways, so within that module I don't see any advantage to going through `g.notebook`.

**Comment by fchapoton** [comment]
Thanks, Erik.

**Comment by kiwifb** [comment]
Solves my issues in Gentoo with flask-0.12.2 /flask-babel-0.11.2.

**Comment by timokau** [comment]
Also allowed me to remove the version pin on `flask-babel` for the nix package. Thank you for your work @fchapoton :)

**Pull request merged**
