### PR TITLE
replacing sgml by html

### PR DESCRIPTION
**Pull request by fchapoton**
and this seems to work.. At least the doctests pass, and sagenb starts and works.

### CODE REVIEW

**Comment by fchapoton** [comment]
Not working, in fact, once tested correctly:

```
File "sagenb/notebook/docHTMLProcessor.py", line 1392, in sagenb.notebook.docHTMLProcessor.docutilsHTMLProcessor.end_script
Failed example:
    p = docutilsHTMLProcessor()
Exception raised:
    Traceback (most recent call last):
      File "/home/chapoton/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 573, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/chapoton/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 983, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sagenb.notebook.docHTMLProcessor.docutilsHTMLProcessor.end_script[1]>", line 1, in <module>
        p = docutilsHTMLProcessor()
    TypeError: __init__() takes at least 2 arguments (1 given)

```

**Comment by fchapoton** [comment]
Not so many failures, but I do not understand them
----------------------------------------------------------------------
sage -t sagenb/notebook/notebook.py  # 13 doctests failed
sage -t sagenb/notebook/docHTMLProcessor.py  # 6 doctests failed
----------------------------------------------------------------------

**Comment by fchapoton** [comment]
This now seems to work. I had to adapt from SGMLParser to HTMLParser by introducing two methods, that mimick the behaviour of SGMLParser.

Needs review. I have forgotten how to access the live documentation in sagenb..

**Comment by kcrisman** [comment]
You go to "Help" and from there there should be a link of some kind to live documentation.

**Comment by fchapoton** [comment]
Does this require having built the doc before ?

**Comment by kcrisman** [comment]
> Does this require having built the doc before ?
>
Probably?  When you click on "Help" you should see at the top a list of
documents like "Tutorial" "Thematic Tutorials" etc.  Click on one of them
and see what happens when you drill down to something with actual examples.
  Unfortunately, I haven't been able to get the live documentation to
actually compute anything for some time, but that may be a browser problem.

**Comment by fchapoton** [comment]
Thanks for the instructions. The interactive help works for me, with the modifications here.

**Comment by fchapoton** [comment]
It seems that sagenb get stuck on anything like

    TamariIntervalPoset?

**Comment by kcrisman** [comment]
Re: the request to look at these, I don't have the ability to currently test this but if it works it should be merged.  It would have been nice to have the whitespace changes in a different place ...

**Comment by embray** [comment]
I haven't tested this; wouldn't even know how except for the one example you gave.  I trust you that it works.

**Comment by fchapoton** [comment]
Thanks Erik. Would it be possible now to make a release ? unless you prefer to wait for #451 ?

**Comment by embray** [comment]
That would probably be best.  Also I don't know who makes "releases" of sagenb.  I'm only merging these because I apparently have permission to do so, but I'm not in any way the maintainer of sagenb, and I'm not sure who is, if anybody.

**Comment by fchapoton** [comment]
Well. Dima has made the previous releases, but has clearly expressed elsewhere his intention to no longer work on sagenb. So somebody else must do the job.

**Comment by embray** [comment]
I suppose I can do it then if you ping me about it later.  We should definitely wait for #451 to be resolved.

**Pull request merged**
