### PR TITLE
add missing __eq__ method for comparison of worksheets

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by jdemeyer** [comment]
I don't think that changing the test is the right thing to do here. I think the problem is that you only implemented `__lt__` instead of all comparison operators (`__eq__`, `__le__`, `__gt__`, ...)

**Comment by embray** [comment]
Right, this was the point of my comment here: https://github.com/sagemath/sagenb/pull/405#r70251556

I probably should have acted on that at the time.

**Comment by fchapoton** [comment]
This should be good now: according to https://docs.python.org/3/library/stdtypes.html#comparisons

it is sufficient to have __eq__ and __lt__

**Comment by fchapoton** [comment]
or maybe we need also to have __ne__ (for python2 compatibility ?)

**Comment by fchapoton** [comment]
ping ?

**Comment by fchapoton** [comment]
ping ?

**Pull request merged**
