### PR TITLE
re-introducing the import of srange

### PR DESCRIPTION
**Pull request by fchapoton**
otherwise the interact will be broken.

sorry for that. This was a wrong move from me.

### CODE REVIEW

**Comment by embray** [comment]
That's rather confusing. Maybe the comment above it should be expanded a bit.  It says "this is needed for `@interact`" but it's not obvious that the "this" is referring to the unused import.

**Comment by fchapoton** [comment]
ping ?

**Comment by embray** [comment]
Ah, I see now.  Is there a reason not to fix the import in notebook/interact.py instead?

**Comment by embray** [comment]
(P.S. @fchapoton in my experience GitHub doesn't send a notification e-mail when new commits are pushed to a PR, but only when a new comment is added)

**Comment by fchapoton** [comment]
Is this what you suggested ?

**Comment by fchapoton** [comment]
hmm, this should really be merged, because in the current state interacts are broken.

**Pull request merged**
