### PR TITLE
No iteritems

### PR DESCRIPTION
**Pull request by fchapoton**
as another step for py3 compatibility, les us remove the calls to iteritems

### CODE REVIEW

**Comment by dimpase** [comment]
Hmm, why do you replace `bla.iteritems()` by `viewitems(bla)`? AFAIK there is `iteritems(bla)` available, and closer mimicking `bla.iteritems()`.

**Comment by fchapoton** [comment]
Well, this was one of the ways suggested in http://python-future.org/compatible_idioms.html

**Comment by dimpase** [comment]
`iteritems` is an iterator, while `viewitems` is not. IMHO the behaviours might differ is the dict is changed in the loop over these, too.

**Comment by fchapoton** [comment]
There is at least one instance where the dict is indeed changed.

**Comment by dimpase** [comment]
So you see, it's pretty serious business, using functions with different behaviour while porting. I'd prefer to stick to ones that match the original behaviour 100%.

**Comment by fchapoton** [comment]
here is a version using iteritems and one list(A.items())

**Comment by dimpase** [comment]
Another question is why you import `from future.utils` rather than `from six`. The latter would work in Python 3 without any changes.

     $ python3
     Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
     [GCC 4.8.4] on linux
     Type "help", "copyright", "credits" or "license" for more information.
     >>> from six import iteritems
     >>> 

    $ python
    Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from six import iteritems
    >>>

**Comment by fchapoton** [comment]
oh, well. If you prefer six, here it is.

**Comment by fchapoton** [comment]
ping ?

**Pull request merged**
