### PR TITLE
enrich canvas3D so that faces can be filled and colored

### PR DESCRIPTION
**Pull request by fchapoton**
I propose a few changes, in coordination with current work on trac ticket #12212. This will allow to display mesh surfaces with one color per face. And this also fills the surface

### CODE REVIEW

**Comment by kcrisman** [comment]
@fchapoton - since Trac 12212 seems to be nearing the finish, can you check whether this is still working properly with the latest changes there?   I'm happy to merge this if everything works for this.

**Comment by fchapoton** [comment]
I will hopefully try later today.

2015-01-07 15:59 GMT+01:00 kcrisman <notifications@github.com>:

**Comment by fchapoton** [comment]
BUT, please, where can I find instructions on how to substitute the
notebook by a personal one ?

2015-01-07 17:19 GMT+01:00 Frédéric Chapoton <fchapoton2@gmail.com>:

**Comment by kcrisman** [comment]
> BUT, please, where can I find instructions on how to substitute the
notebook by a personal one ?

I'm not sure what you mean.  The readme and hacking files should be accurate (or at least work) now, I used them all fall, if that is what you are referring to.  @jdemeyer suggests even simpler instructions of just cloning, going into a sage shell (`sage -sh`) and then doing `sage -python setup.py develop` or something like that, but I haven't tried that.

**Comment by fchapoton** [comment]
Oh, I see, thanks. You mean that page:

https://github.com/sagemath/sagenb/blob/master/HACKING.rst

I think I will manage to get the correct sagenb git branch and use it. But
not right now.



2015-01-07 17:24 GMT+01:00 kcrisman <notifications@github.com>:

**Comment by kcrisman** [comment]
Alternately, in this case with such small changes, you could just type them in by hand in the site-packages egg for sagenb and test them that way.  I would test it myself before merging anyway, but I don't want to do so until I know the author thinks it works :smiley:

**Comment by kcrisman** [comment]
> Really ? I was thinking that I still have changed the behaviour of color, because after 12212 is is given by sage as say '#ff0000` and berfore that it was given by `ff0000` and the notebook was adding the #.. Could you please check that you can set the color to red or orange instead of the default blue ?

I think this is almost ready, as it seems to work fine with the Trac ticket.  Did you mean here to try

```
sphere(color='#ffff00').show(viewer='canvas3d')
sphere(color='orange').show(viewer='canvas3d')
P1 = ParametricSurface(g, (srange(-10,10,0.1), srange(-5,5.0,0.1)),color='orange')
P1.show(viewer='canvas3d') 
```

(which both work, along with the colormap coloring) or something else?

**Comment by fchapoton** [comment]
sphere(color='#ffff00').show(viewer='canvas3d')

works (yellow sphere)

sphere(color='orange').show(viewer='canvas3d')

works (orange sphere)

P1 = ParametricSurface(g, (srange(-10,10,0.1),
srange(-5,5.0,0.1)),color='orange')
P1.show(viewer='canvas3d')

works (orange surface)

So everything is fine with canvas

2015-01-07 20:50 GMT+01:00 kcrisman <notifications@github.com>:

**Comment by kcrisman** [comment]
Great!  I'll just wait on a positive review for the Trac ticket, then.

**Comment by kcrisman** [comment]
This works beautifully with the Trac changes, so I'll go ahead and merge this (I can revert it if need be but I don't see any problems cropping up there any more now that jmol has been upgraded).

**Pull request merged**
