### PR TITLE
adding methods __ne__ and __gt__ for comparison of worksheets

### PR DESCRIPTION
**Pull request by fchapoton**
trying to fix the comparison flaky doctest (maybe one also should add the total ordering decorator ?)

### CODE REVIEW

**Comment by dimpase** [comment]
With this patch at least the failures become reproducible. This is using W1 and W2 as defined in the lines
525-525 of the patched file:
{{{
sage: W1
admin/1: [Cell 1: in=, out=]
sage: W2
admin/0: [Cell 1: in=, out=]
sage: W1>W2
True
sage: W1>=W2
False
}}}

**Comment by fchapoton** [comment]
This probably means that we also have to add __le__ and __ge__.

**Comment by dimpase** [comment]
Do you mean to say that Python does not know that `le==lt || eq`? You also metioned @total_ordering,
what is this? Perhaps exactly to tell it to derive `le` and `ge` ? Where should it go?

**Comment by fchapoton** [comment]
@total_ordering is a class decorator that does the job of generating every comparison operator from just a minimal amount of them. We can also just define all the operators ourselves.

**Comment by dimpase** [comment]
it seems it started in https://trac.sagemath.org/ticket/16537 - that `@total_ordering` thing

**Comment by dimpase** [comment]
now even more doctests on comparison fail
```
sage -t --long --warn-long 47.5 local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py", line 502, in sagenb.notebook.worksheet.Worksheet.__lt__
Failed example:
    W1 < W2
Expected:
    True
Got:
    False
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py", line 504, in sagenb.notebook.worksheet.Worksheet.__lt__
Failed example:
    W2 < W1
Expected:
    False
Got:
    True
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py", line 527, in sagenb.notebook.worksheet.Worksheet.__gt__
Failed example:
    W1 > W2
Expected:
    False
Got:
    True
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py", line 529, in sagenb.notebook.worksheet.Worksheet.__gt__
Failed example:
    W2 > W1
Expected:
    True
Got:
    False
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py", line 552, in sagenb.notebook.worksheet.Worksheet.__le__
Failed example:
    W1 <= W2
Expected:
    True
Got:
    False
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py", line 554, in sagenb.notebook.worksheet.Worksheet.__le__
Failed example:
    W2 <= W1
Expected:
    False
Got:
    True
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py", line 577, in sagenb.notebook.worksheet.Worksheet.__ge__
Failed example:
    W1 >= W2
Expected:
    False
Got:
    True
**********************************************************************
File "local/lib/python2.7/site-packages/sagenb/notebook/worksheet.py", line 579, in sagenb.notebook.worksheet.Worksheet.__ge__
Failed example:
    W2 >= W1
Expected:
    True
Got:
    False
**********************************************************************
4 items had failures:
   2 of   7 in sagenb.notebook.worksheet.Worksheet.__ge__
   2 of   7 in sagenb.notebook.worksheet.Worksheet.__gt__
   2 of   7 in sagenb.notebook.worksheet.Worksheet.__le__
   2 of   7 in sagenb.notebook.worksheet.Worksheet.__lt__
    [579 tests, 8 failures, 7.58 s]
```
Perhaps it's just different ordering now, for some reason?

**Comment by fchapoton** [comment]
What are the results of W1.filename() and W2.filename() ?

**Comment by dimpase** [comment]
```
sage: W1.filename()
'admin/1'
sage: W2.filename()
'admin/0'
```

**Comment by dimpase** [comment]
wait...

**Comment by fchapoton** [comment]
so there is no "test1" or "test2" in the name of the file. Ok. Then of course all doctests are reversed.

**Comment by dimpase** [comment]
OK, this works.

**Comment by jdemeyer** [comment]
> you mean to say that Python does not know that le==lt || eq?

No. Python does not make any assumptions on implications without the various rich comparison methods. In fact, some Sage elements (notably intervals) satisfy `x <= y` but neither `x < y` nor `x == y`.

The ''only'' thing that is assumed by Python is that the order can be reversed: `x <= y` is assumed to be equivalent to `y >= x`.

See https://www.python.org/dev/peps/pep-0207/ for more information.

**Pull request merged**
