### PR TITLE
SystemExit is included in Python3

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by fchapoton** [comment]
and in fact maybe also in python2 ?

**Comment by jdemeyer** [comment]
Please elaborate: what is this trying to fix?

**Comment by fchapoton** [comment]
This is trying to fix the notebook for use with python3 sage. The current import is not working in python3.
```

Python 3.5.3 (default, Sep 14 2017, 22:58:41) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from exceptions import SystemExit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'exceptions'
>>> 

```

**Comment by fchapoton** [comment]
indeed.

**Pull request merged**
